"""schema inicial auth

Revision ID: e44b06c264c5
Revises: 
Create Date: 2026-05-04 19:20:10.702183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'e44b06c264c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('falhas_consecutivas', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sessao_versao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('convites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('criado_por', sa.String(length=36), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_convites_token_hash'), ['token_hash'], unique=True)

    op.create_table('eventos_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('email_tentado', sa.String(length=255), nullable=True),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_auth_criado_em'), ['criado_em'], unique=False)

    op.create_table('tokens_reset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_reset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_reset_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens_reset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_reset_token_hash'))

    op.drop_table('tokens_reset')
    with op.batch_alter_table('eventos_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_auth_criado_em'))

    op.drop_table('eventos_auth')
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convites_token_hash'))
        batch_op.drop_index(batch_op.f('ix_convites_email'))

    op.drop_table('convites')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
